# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ╔╦╗╦═╗╔═╗╦  ╦╦╔═╗ ┬ ┬┌┬┐┬                           #
#    ║ ╠╦╝╠═╣╚╗╔╝║╚═╗ └┬┘││││                           #
#  o ╩ ╩╚═╩ ╩ ╚╝ ╩╚═╝o ┴ ┴ ┴┴─┘                         #
#                                                       #
# This file configures Travis CI.                       #
# (i.e. how we run the tests... mainly)                 #
#                                                       #
# https://docs.travis-ci.com/user/customizing-the-build #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

language: node_js

node_js:
  - "8"
  - "10"
  - "node"

services: mssql
addons:
  mssql: "2017"
sudo: false
env:
  - DB_USER=sails DB_PASS='sails'
before_script:
  - mssql -c 'create database "sails-test";' -U sa

branches:
  only:
    - master

notifications:
  email:
    - ci@sailsjs.com
