language: node_js

node_js:
  - 12

env:
  global:
    - SA_PASSWORD=Password1
    - MSSQL_HOST=localhost
    - MSSQL_PORT=1433
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=${SA_PASSWORD}
    - MSSQL_DB=sails-test

services:
  - docker

before_script:
  - docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$SA_PASSWORD" -p 1433:1433 -d --name=sqlserver --name=mssql-server-2017-latest-ubuntu
  - docker cp test/docker sqlserver:/sails-sqlserver-adapter
  - docker exec -it -u root sqlserver sh -c 'chmod 777 /sails-sqlserver-adapter/*.sh'
  - sleep 60s
  - docker exec -it -u root sqlserver sh -c /sails-sqlserver-adapter/travis-test.sh
